// Image paths prefixed with BASE_URL so they work on any deployment subpath.
// import.meta.env.BASE_URL is resolved by Vite at build time (e.g. "/gabbars-restaurant/").

const base = import.meta.env.BASE_URL;

export const IMAGES = {
  logo: `${base}assets/generated/gabbars-logo-transparent.dim_400x200.png`,
  butterChicken: `${base}assets/generated/butter-chicken.dim_600x400.jpg`,
  chickenBiryani: `${base}assets/generated/chicken-biryani.dim_600x400.jpg`,
  chickenBurger: `${base}assets/generated/chicken-burger.dim_600x400.jpg`,
  chickenLollipop: `${base}assets/generated/chicken-lollipop.dim_600x400.jpg`,
  chickenRoll2: `${base}assets/generated/chicken-roll-2.dim_600x400.jpg`,
  chickenRoll: `${base}assets/generated/chicken-roll.dim_600x400.jpg`,
  chickenSeekh: `${base}assets/generated/chicken-seekh.dim_600x400.jpg`,
  chillyChicken: `${base}assets/generated/chilly-chicken.dim_600x400.jpg`,
  chillyPaneer: `${base}assets/generated/chilly-paneer.dim_600x400.jpg`,
  choleBhature: `${base}assets/generated/chole-bhature.dim_600x400.jpg`,
  cornSaltPepper: `${base}assets/generated/corn-salt-pepper.dim_600x400.jpg`,
  dahiKebab: `${base}assets/generated/dahi-kebab.dim_600x400.jpg`,
  dalMakhani: `${base}assets/generated/dal-makhani.dim_600x400.jpg`,
  eggRoll: `${base}assets/generated/egg-roll.dim_600x400.jpg`,
  frenchFries: `${base}assets/generated/french-fries.dim_600x400.jpg`,
  galleryBiryani: `${base}assets/generated/gallery-biryani.dim_800x600.jpg`,
  galleryDining: `${base}assets/generated/gallery-dining.dim_800x600.jpg`,
  galleryInterior1: `${base}assets/generated/gallery-interior-1.dim_800x600.jpg`,
  galleryMakhani: `${base}assets/generated/gallery-makhani.dim_800x600.jpg`,
  galleryStarters: `${base}assets/generated/gallery-starters.dim_800x600.jpg`,
  galleryTandoor: `${base}assets/generated/gallery-tandoor.dim_800x600.jpg`,
  gulabJamun: `${base}assets/generated/gulab-jamun.dim_600x400.jpg`,
  hakkaNoodles: `${base}assets/generated/hakka-noodles.dim_600x400.jpg`,
  haraBharaKabab: `${base}assets/generated/hara-bhara-kabab.dim_600x400.jpg`,
  heroBanner: `${base}assets/generated/hero-banner.dim_1400x700.jpg`,
  honeyChilliPotato: `${base}assets/generated/honey-chilli-potato.dim_600x400.jpg`,
  hotSourSoup: `${base}assets/generated/hot-sour-soup.dim_600x400.jpg`,
  manchowSoup: `${base}assets/generated/manchow-soup.dim_600x400.jpg`,
  margheritaPizza2: `${base}assets/generated/margherita-pizza-2.dim_600x400.jpg`,
  margheritaPizza: `${base}assets/generated/margherita-pizza.dim_600x400.jpg`,
  mixVegRaita: `${base}assets/generated/mix-veg-raita.dim_600x400.jpg`,
  mushroomTikka: `${base}assets/generated/mushroom-tikka.dim_600x400.jpg`,
  muttonBiryani: `${base}assets/generated/mutton-biryani.dim_600x400.jpg`,
  muttonSeekh: `${base}assets/generated/mutton-seekh.dim_600x400.jpg`,
  naanBread: `${base}assets/generated/naan-bread.dim_600x400.jpg`,
  nonvegThali: `${base}assets/generated/nonveg-thali.dim_600x400.jpg`,
  paneerPakora: `${base}assets/generated/paneer-pakora.dim_600x400.jpg`,
  paneerParantha: `${base}assets/generated/paneer-parantha.dim_600x400.jpg`,
  paneerRoll: `${base}assets/generated/paneer-roll.dim_600x400.jpg`,
  paneerSandwich: `${base}assets/generated/paneer-sandwich.dim_600x400.jpg`,
  paneerTikkaPizza: `${base}assets/generated/paneer-tikka-pizza.dim_600x400.jpg`,
  paneerTikka: `${base}assets/generated/paneer-tikka.dim_600x400.jpg`,
  pineappleRaita: `${base}assets/generated/pineapple-raita.dim_600x400.jpg`,
  plainCurd: `${base}assets/generated/plain-curd.dim_600x400.jpg`,
  redSaucePasta: `${base}assets/generated/red-sauce-pasta.dim_600x400.jpg`,
  seekhKebab: `${base}assets/generated/seekh-kebab.dim_600x400.jpg`,
  soyaChaap: `${base}assets/generated/soya-chaap.dim_600x400.jpg`,
  tandooriAloo: `${base}assets/generated/tandoori-aloo.dim_600x400.jpg`,
  tandooriChicken: `${base}assets/generated/tandoori-chicken.dim_600x400.jpg`,
  tangriKebab: `${base}assets/generated/tangri-kebab.dim_600x400.jpg`,
  tomatoSoup: `${base}assets/generated/tomato-soup.dim_600x400.jpg`,
  vegBiryani: `${base}assets/generated/veg-biryani.dim_600x400.jpg`,
  vegBurger: `${base}assets/generated/veg-burger.dim_600x400.jpg`,
  vegCheeseSandwich: `${base}assets/generated/veg-cheese-sandwich.dim_600x400.jpg`,
  vegPakora: `${base}assets/generated/veg-pakora.dim_600x400.jpg`,
  vegRoll: `${base}assets/generated/veg-roll.dim_600x400.jpg`,
  vegThali: `${base}assets/generated/veg-thali.dim_600x400.jpg`,
  whiteSaucePasta: `${base}assets/generated/white-sauce-pasta.dim_600x400.jpg`,
  biryani: `${base}assets/generated/biryani.dim_600x400.jpg`,
  // Hero upload
  heroPage: `${base}assets/uploads/hero-page-1.JPG`,
};
