/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Reservation = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
});
export const OrderType = IDL.Variant({
  'pickup' : IDL.Null,
  'delivery' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'orderType' : OrderType,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  'addReservation' : IDL.Func([IDL.Text, Time, IDL.Nat, IDL.Text], [], []),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, OrderType, IDL.Vec(OrderItem), IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Reservation = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
  });
  const OrderType = IDL.Variant({ 'pickup' : IDL.Null, 'delivery' : IDL.Null });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'orderType' : OrderType,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    'addReservation' : IDL.Func([IDL.Text, Time, IDL.Nat, IDL.Text], [], []),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, OrderType, IDL.Vec(OrderItem), IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };